# ============================================================================ #
# ================================ CONFIG FILE =============================== #
# ============================================================================ #

# --------------------------------------------------------------------- #
# -------------------------------- DATA ------------------------------- #
# --------------------------------------------------------------------- #

# ___ base ___ #
dataset_properties: &dataset_properties
  name: ClassificationROIDataset
  data_dir: /home/nicola/data/meso
  type: ndpi
  size: &size 128

in_channels: &data_channels 3

# ___ dataset ___ #
dataset: &dataset
  pred:
    <<: *dataset_properties
    split:
      - 0
      - 1
    splitting: stratified

# ___ datamodule ___ #
datamodule:
  dataset_hparams: *dataset
  workers:
    pred: 12
  batch_sizes:
    pred: 1


# --------------------------------------------------------------------- #
# -------------------------- LIGHTNING MODEL -------------------------- #
# --------------------------------------------------------------------- #

# ___ backbone ___ #
backbone_params: &backbone
  name: ResNet
  block: BasicBlock
  layers:
    - 2
    - 2
    - 2
    - 2
  global_avg_pool: True

# ___ model ___ #
model:
  name: PredictionModule
  backbone_hparams: *backbone
  input_shape:
    - *data_channels
    - *size
    - *size
  metta: False

# ___ load pretrained ___ # (Optional)
pretrained:
  pretrained_model: /home/nicola/ssrllib_logs/meso_pretext_rotation/lightning_logs/version_0/checkpoints/epoch=77-step=1715.ckpt
  drop_head: True
  freeze_backbone: True


# --------------------------------------------------------------------- #
# ------------------------- RUN CONFIGURATION ------------------------- #
# --------------------------------------------------------------------- #

# ___ trainer ___ #

trainer:
  default_root_dir: /home/nicola/ssrllib_logs/
  max_epochs: 100
  gpus: 1
  strategy: dp
  log_every_n_steps: 1



# --------------------------------------------------------------------- #
# ------------------------- PREDICTION CONFIG ------------------------- #
# --------------------------------------------------------------------- #

splits:
  test_size: 0.4
  train_sizes: 
    - 0.1
    - 0.2
    - 0.5
    - 1 # 60% of data (we consider this full supervision)

param_grid: &param_grid
  classifier__kernel:
    - rbf
    - linear
  classifier__C:
    - 0.1
    - 1
    - 10
    - 100
    - 1000
  classifier__random_state:
    - 0
  upsampler__random_state:
    - 0
  downsampler__sampling_strategy:
    - majority
    - auto
  downsampler__n_neighbors:
    - 1
    - 2
    - 3

grid_search_hparams:
  cv: 5
  n_jobs: 6
  param_grid: *param_grid
  scoring: accuracy

seeder:
  seed: 0
  workers: True