# ============================================================================ #
# ================================ CONFIG FILE =============================== #
# ============================================================================ #

# --------------------------------------------------------------------- #
# -------------------------------- DATA ------------------------------- #
# --------------------------------------------------------------------- #

# ___ base ___ #
dataset_properties: &dataset_properties
  name: ClassificationROIDataset
  data_dir: /home/nicola/data/meso
  type: ndpi
  size: &size 128

in_channels: &data_channels 3

# ___ dataset ___ #
dataset: &dataset
  train:
    <<: *dataset_properties
    split:
      - 0
      - 0.06
    splitting: stratified
  val:
    <<: *dataset_properties
    split:
      - 0.6
      - 0.8
    splitting: stratified
  test:
    <<: *dataset_properties
    split:
      - 0.8
      - 1
    splitting: stratified

# ___ datamodule ___ #
datamodule:
  dataset_hparams: *dataset
  workers:
    train: 12
    val: 12
    test: 12
  batch_sizes:
    train: 32
    val: 32
    test: 32

# ___ transforms ___ # (Optional)
transforms:
  - name: RandomRotate90
    prob: 0.5
  - name: RandomFlip
    prob: 0.5
    dim: 0
  - name: RandomFlip
    prob: 0.5
    dim: 1
  - name: ContrastAdjust
    adj: 0.1
  - name: AddNoise
    sigma_max: 0.05


# --------------------------------------------------------------------- #
# --------------------------- OPTIMIZATION ---------------------------- #
# --------------------------------------------------------------------- #

# ___ optimizer ___ #
optimizer: &optimizer
  name: Adam
  lr: 1.0e-06

# ___ scheduler ___ #
scheduler: &scheduler
  name: ReduceLROnPlateau
  monitor: val/Accuracy
  patience: 10
  factor: 0.5
  mode: max

# ___ loss ___ #
loss: &loss
  name: CELoss

# ___ metric ___ #
metric: &metric
  name: Accuracy


# --------------------------------------------------------------------- #
# -------------------------- LIGHTNING MODEL -------------------------- #
# --------------------------------------------------------------------- #

# ___ backbone ___ #
backbone_params: &backbone
  name: ResNet
  block: BasicBlock
  layers:
    - 2
    - 2
    - 2
    - 2
  global_avg_pool: True

# ___ head ___ #
head_params: &head
  name: LinearHead
  in_features: 512
  task_classes: 2

# ___ model ___ #
model:
  name: TrainingModule
  backbone_hparams: *backbone
  head_hparams: *head
  optimizer_hparams: *optimizer
  scheduler_hparams: *scheduler
  loss_hparams: *loss
  metric_hparams: *metric
  input_shape:
    - *data_channels
    - *size
    - *size


# ------------------------------------------------------------- #
# ------------------------- CALLBACKS ------------------------- #
# ------------------------------------------------------------- #

callbacks:
  # ___ checkpoint ___ #
  - name: ModelCheckpoint
    save_top_k: 1
    verbose: True
    monitor: val/Accuracy
    mode: max
    every_n_epochs: 1
  # ___ early stopping ___ #
  - name: EarlyStopping
    monitor: val/Accuracy
    min_delta: 0.005
    patience: 21
    mode: max
  # ___ lr monitor ___ #
  - name: LearningRateMonitor


# --------------------------------------------------------------------- #
# ------------------------- RUN CONFIGURATION ------------------------- #
# --------------------------------------------------------------------- #

# ___ trainer ___ #

trainer:
  default_root_dir: /home/nicola/ssrllib_logs/
  max_epochs: 100
  gpus: 1
  strategy: dp
  log_every_n_steps: 1

seeder: 
  seed: 0
  workers: True
