seed_everything: 0

data:
  class_path: ssrllib.data.datamodules.PredictionDataModule
  init_args:
    batch_size: 1
    workers: 12
    dataset_pred:
      class_path: &dataset_class_path ssrllib.data.datasets.ClassificationDataset
      init_args: &dataset_init_args
        data_dir: &data_dir data/crc_root_folder
        type: png
        size: &input_size 128
        split: [0, 1]
        splitting: stratified

model:
  class_path: ssrllib.models.modules.PredictionModule
  init_args:
    backbone:
      class_path: ssrllib.models.resnet.ResNet
      init_args:
        block: BasicBlock
        layers: [2, 2, 2, 2]
        global_avg_pool: True
    head:
      class_path: sklearn.svm.SVC
    input_shape: [3, *input_size, *input_size]
    splits:
      test: [0.4]
      train: [0.05, 0.1, 0.2, 0.5, 1]
    samplers:
      - - undersampler
        - class_path: imblearn.under_sampling.EditedNearestNeighbours
      - - upsampler
        - class_path: imblearn.over_sampling.SMOTE
    param_grid:
      classifier__kernel: [rbf]
      classifier__C: [1, 10, 100, 1000]
      classifier__random_state: [0]
      # upsampler__random_state: [0]
      # undersampler__sampling_strategy: [majority, auto]
      # undersampler__n_neighbors: [1, 2, 3]
    grid_search_params:
      cv: 3
      n_jobs: 12
      scoring: accuracy
      # verbose: 4
    metta: False
    ckpt_path: checkpoints/epoch=31-step=7679.ckpt

trainer:
  default_root_dir: logs/crc/downstream
  max_epochs: &epochs 100
  gpus: 1
  strategy: dp
  log_every_n_steps: 1
  enable_progress_bar: True
